# Generated by Django 5.0.7 on 2026-05-14 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('managed_by', models.ManyToManyField(blank=True, related_name='managed_shops', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_shop_shop',
                'permissions': [('can_manage_assigned_shops', 'Can manage shops assigned to user (multi-shop access)')],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_score', models.PositiveIntegerField(default=1000000)),
                ('score_for_purchase', models.PositiveBigIntegerField(default=1)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='module_shop.shop')),
            ],
            options={
                'db_table': 'module_shop_score',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='module_shop.shop')),
            ],
            options={
                'db_table': 'module_shop_branch',
                'ordering': ('name',),
                'permissions': [('manage_all_branches', 'Can manage all branches of accessible shops')],
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['owner'], name='shop_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['shop', 'is_active'], name='branch_shop_active_idx'),
        ),
    ]
