# Generated by Django 5.0.7 on 2026-05-14 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_account', '0001_initial'),
        ('module_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_logs', to='module_product.product'),
        ),
        migrations.AddField(
            model_name='userscorelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
