# Generated by Django 5.0.7 on 2026-05-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='module_shop.branch')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='module_shop.shop')),
            ],
            options={
                'db_table': 'module_product_category',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('second_id', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='module_shop.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='module_product.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='module_shop.shop')),
            ],
            options={
                'db_table': 'module_product_product',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['shop', 'is_active'], name='category_shop_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='product_shop_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch'], name='product_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('branch', 'second_id')},
        ),
    ]
