# Generated by Django 5.0.7 on 2026-05-16 08:18
# Idempotent: safe when is_offerable / CustomerProductOffer already exist in the DB.

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import ProjectState


def _column_exists(schema_editor, table: str, column: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(f'PRAGMA table_info("{table}")')
            return any(row[1] == column for row in cursor.fetchall())
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = CURRENT_SCHEMA()
              AND table_name = %s
              AND column_name = %s
            """,
            [table, column],
        )
        return cursor.fetchone() is not None


def _table_exists(schema_editor, table: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s",
                [table],
            )
        else:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = CURRENT_SCHEMA()
                  AND table_name = %s
                """,
                [table],
            )
        return cursor.fetchone() is not None


def _create_customer_product_offer_operation():
    return migrations.CreateModel(
        name="CustomerProductOffer",
        fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("phone_number", models.CharField(db_index=True, max_length=11)),
            ("offer_rate", models.PositiveIntegerField(default=0)),
            ("is_active", models.BooleanField(default=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            (
                "product",
                models.ForeignKey(
                    limit_choices_to={"is_active": True, "is_offerable": True},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="customer_offers",
                    to="module_product.product",
                ),
            ),
        ],
        options={
            "db_table": "module_product_customerproductoffer",
            "indexes": [
                models.Index(fields=["phone_number", "is_active"], name="cust_offer_phone_active_idx"),
            ],
            "unique_together": {("phone_number", "product")},
        },
    )


def apply_0002_forwards(apps, schema_editor):
    product_table = "module_product_product"
    offer_table = "module_product_customerproductoffer"

    if not _column_exists(schema_editor, product_table, "is_offerable"):
        product_model = apps.get_model("module_product", "Product")
        field = models.BooleanField(
            default=False,
            help_text="If true, this product can appear in customer club special offers.",
        )
        field.set_attributes_from_name("is_offerable")
        schema_editor.add_field(product_model, field)

    if not _table_exists(schema_editor, offer_table):
        operation = _create_customer_product_offer_operation()
        old_state = ProjectState.from_apps(apps)
        new_state = old_state.clone()
        operation.state_forwards("module_product", new_state)
        operation.database_forwards("module_product", schema_editor, old_state, new_state)


def apply_0002_backwards(apps, schema_editor):
    product_table = "module_product_product"
    offer_table = "module_product_customerproductoffer"

    if _table_exists(schema_editor, offer_table):
        operation = _create_customer_product_offer_operation()
        old_state = ProjectState.from_apps(apps)
        new_state = old_state.clone()
        operation.state_forwards("module_product", old_state)
        operation.database_forwards("module_product", schema_editor, new_state, old_state)

    if _column_exists(schema_editor, product_table, "is_offerable"):
        product_model = apps.get_model("module_product", "Product")
        field = product_model._meta.get_field("is_offerable")
        schema_editor.remove_field(product_model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("module_product", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(apply_0002_forwards, apply_0002_backwards),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="is_offerable",
                    field=models.BooleanField(
                        default=False,
                        help_text="If true, this product can appear in customer club special offers.",
                    ),
                ),
                _create_customer_product_offer_operation(),
            ],
        ),
    ]
