# Generated by Django 5.0.7 on 2026-05-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_product', '0002_product_is_offerable_customerproductoffer'),
        ('module_shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='module_shop.branch'),
        ),
        migrations.CreateModel(
            name='SpecialOfferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offer_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_product_specialoffertransaction',
            },
        ),
        migrations.CreateModel(
            name='UserSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_rate', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(limit_choices_to={'is_offerable': True}, on_delete=django.db.models.deletion.CASCADE, to='module_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroffer_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_product_userspecialoffer',
                'indexes': [models.Index(fields=['user', 'product'], name='user_offer_user_product_idx')],
            },
        ),
    ]
