# Generated by Django 5.0.7 on 2026-05-19 16:26

from django.conf import settings
from django.db import migrations


def migrate_customer_offers_to_user_special(apps, schema_editor):
    CustomerProductOffer = apps.get_model("module_product", "CustomerProductOffer")
    UserSpecialOffer = apps.get_model("module_product", "UserSpecialOffer")
    User = apps.get_model("module_account", "User")

    for offer in CustomerProductOffer.objects.select_related("product").iterator():
        if not offer.is_active:
            continue
        user = User.objects.filter(phone_number=offer.phone_number).order_by("id").first()
        if not user:
            continue
        UserSpecialOffer.objects.update_or_create(
            user_id=user.id,
            product_id=offer.product_id,
            defaults={"offer_rate": offer.offer_rate or 0},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('module_product', '0003_alter_product_branch_specialoffertransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_customer_offers_to_user_special, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='userspecialoffer',
            unique_together={('user', 'product')},
        ),
        migrations.DeleteModel(
            name='CustomerProductOffer',
        ),
    ]
