# Generated by Django 5.0.7 on 2026-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_product', '0007_product_image_storage_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffertransaction',
            name='delta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialoffertransaction',
            name='reason',
            field=models.CharField(choices=[('special_offer', 'Special offer'), ('purchase', 'Purchase'), ('admin_adjust', 'Admin adjust')], max_length=32),
        ),
    ]
