# Generated by Django 5.0.7 on 2026-05-14 18:29

import django.db.models.deletion
import module_product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='module_shop.shop')),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('second_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to=module_product.models.product_image_upload_to)),
                ('is_offerable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='module_product.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOfferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offer_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_rate', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(limit_choices_to={'is_offerable': True}, on_delete=django.db.models.deletion.CASCADE, to='module_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroffer_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
