# Generated by Django 5.0.7 on 2026-05-16 08:29

import module_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_product', '0003_product_second_id_not_globally_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=module_product.models.product_image_upload_to),
        ),
    ]
