# Generated by Django 5.0.7 on 2026-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_product', '0005_remove_management_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remote_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
