# Generated by Django 5.0.7 on 2026-05-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_product', '0008_product_image_storage_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffertransaction',
            name='delta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialoffertransaction',
            name='reason',
            field=models.CharField(choices=[('special_offer', 'Special offer'), ('purchase', 'Purchase'), ('admin_adjust', 'Admin adjust')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userspecialoffer',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_offerable': True}, on_delete=django.db.models.deletion.CASCADE, to='module_product.product'),
        ),
    ]
