# Generated by Django 5.0.7 on 2026-05-14 18:29
#
# Idempotent on PostgreSQL/SQLite: if M2M through tables already exist (legacy DB),
# DDL is skipped so migrate does not fail with DuplicateTable.

from django.db import migrations, models


def _pg_table_exists(schema_editor, table: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_tables WHERE schemaname = current_schema() AND tablename = %s",
            [table],
        )
        return cursor.fetchone() is not None


def _sqlite_table_exists(schema_editor, table: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s",
            [table],
        )
        return cursor.fetchone() is not None


def _table_exists(schema_editor, table: str) -> bool:
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        return _pg_table_exists(schema_editor, table)
    if vendor == "sqlite":
        return _sqlite_table_exists(schema_editor, table)
    return False


def _exec(schema_editor, sql: str):
    schema_editor.execute(sql)


def apply_m2m_and_indexes_if_missing(apps, schema_editor):
    """
    Create User M2M through tables and indexes only when missing (fresh DB).
    Legacy databases that already have these objects are left unchanged.
    """
    vendor = schema_editor.connection.vendor
    if vendor not in ("postgresql", "sqlite"):
        return

    # --- Through tables (names match Django defaults for module_account.User) ---
    if vendor == "postgresql":
        if not _table_exists(schema_editor, "module_account_user_allowed_branches"):
            _exec(
                schema_editor,
                """
                CREATE TABLE "module_account_user_allowed_branches" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "branch_id" bigint NOT NULL REFERENCES "module_shop_branch" ("id") DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT "module_account_user_allowed_branches_user_id_branch_id_uniq" UNIQUE ("user_id", "branch_id")
                );
                """,
            )
        if not _table_exists(schema_editor, "module_account_user_managed_shops_all_branches"):
            _exec(
                schema_editor,
                """
                CREATE TABLE "module_account_user_managed_shops_all_branches" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "shop_id" bigint NOT NULL REFERENCES "module_shop_shop" ("id") DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT "module_account_user_managed_shops_all_branches_user_id_shop_id_uniq" UNIQUE ("user_id", "shop_id")
                );
                """,
            )
        if not _table_exists(schema_editor, "module_account_user_groups"):
            _exec(
                schema_editor,
                """
                CREATE TABLE "module_account_user_groups" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT "module_account_user_groups_user_id_group_id_uniq" UNIQUE ("user_id", "group_id")
                );
                """,
            )
        if not _table_exists(schema_editor, "module_account_user_user_permissions"):
            _exec(
                schema_editor,
                """
                CREATE TABLE "module_account_user_user_permissions" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT "module_account_user_user_permissions_user_id_permission_id_uniq" UNIQUE ("user_id", "permission_id")
                );
                """,
            )
        _exec(
            schema_editor,
            'CREATE INDEX IF NOT EXISTS "module_acco_phone_n_0f0b9f_idx" ON "module_account_user" ("phone_number");',
        )
        _exec(
            schema_editor,
            'CREATE INDEX IF NOT EXISTS "module_acco_card_ui_ea04ca_idx" ON "module_account_user" ("card_uid");',
        )
        return

    # SQLite
    if not _table_exists(schema_editor, "module_account_user_allowed_branches"):
        _exec(
            schema_editor,
            """
            CREATE TABLE "module_account_user_allowed_branches" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                "branch_id" bigint NOT NULL REFERENCES "module_shop_branch" ("id") DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("user_id", "branch_id")
            );
            """,
        )
    if not _table_exists(schema_editor, "module_account_user_managed_shops_all_branches"):
        _exec(
            schema_editor,
            """
            CREATE TABLE "module_account_user_managed_shops_all_branches" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                "shop_id" bigint NOT NULL REFERENCES "module_shop_shop" ("id") DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("user_id", "shop_id")
            );
            """,
        )
    if not _table_exists(schema_editor, "module_account_user_groups"):
        _exec(
            schema_editor,
            """
            CREATE TABLE "module_account_user_groups" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("user_id", "group_id")
            );
            """,
        )
    if not _table_exists(schema_editor, "module_account_user_user_permissions"):
        _exec(
            schema_editor,
            """
            CREATE TABLE "module_account_user_user_permissions" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "user_id" bigint NOT NULL REFERENCES "module_account_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("user_id", "permission_id")
            );
            """,
        )
    _exec(
        schema_editor,
        'CREATE INDEX IF NOT EXISTS "module_acco_phone_n_0f0b9f_idx" ON "module_account_user" ("phone_number");',
    )
    _exec(
        schema_editor,
        'CREATE INDEX IF NOT EXISTS "module_acco_card_ui_ea04ca_idx" ON "module_account_user" ("card_uid");',
    )


def unapply_m2m_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("module_account", "0001_initial"),
        ("module_shop", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(apply_m2m_and_indexes_if_missing, unapply_m2m_noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="allowed_branches",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="allowed_users",
                        to="module_shop.branch",
                    ),
                ),
                migrations.AddField(
                    model_name="user",
                    name="groups",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                migrations.AddField(
                    model_name="user",
                    name="managed_shops_all_branches",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="all_branch_managers",
                        to="module_shop.shop",
                    ),
                ),
                migrations.AddField(
                    model_name="user",
                    name="user_permissions",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                migrations.AddIndex(
                    model_name="user",
                    index=models.Index(fields=["phone_number"], name="module_acco_phone_n_0f0b9f_idx"),
                ),
                migrations.AddIndex(
                    model_name="user",
                    index=models.Index(fields=["card_uid"], name="module_acco_card_ui_ea04ca_idx"),
                ),
            ],
        ),
    ]
