# Generated by Django 5.0.7 on 2026-05-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_account', '0004_user_created_for_shop'),
        ('module_product', '0002_product_is_offerable_customerproductoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_verification_code',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_verification_code_last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('special_offer', 'Special offer'), ('purchase', 'Purchase'), ('admin_adjust', 'Admin adjust')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_logs', to='module_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_account_userscorelog',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
