# Generated by Django 5.0.7 on 2026-05-19 13:59

import module_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('module_account', '0006_user_role_hierarchy'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branchmanager',
            managers=[
                ('objects', module_account.models.BranchManagerManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='enduser',
            managers=[
                ('objects', module_account.models.EndUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shopmanager',
            managers=[
                ('objects', module_account.models.ShopManagerManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', module_account.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('shop_manager', 'Shop manager'), ('branch_manager', 'Branch manager'), ('end_user', 'End user')], db_index=True, default='branch_manager', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='module_acco_role_fb5c0e_idx'),
        ),
    ]
