"""
Django settings for CustomerClub project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _env(name, default=None, aliases=()):
    for candidate in (name, *aliases):
        value = os.getenv(candidate)
        if value not in (None, ""):
            return value
    return default


_load_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    "django-insecure--w)l!&8d4@!fha**l75wq6zs@8@a1fcr4t*g4pum9g645#7l5y",
    aliases=("SECRET_KEY",),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

# OpenAPI/Swagger (drf-spectacular) — off by default for faster kiosk API startup.
ENABLE_OPENAPI = _env("ENABLE_OPENAPI", "false").lower() in ("1", "true", "yes", "on")

_allowed = _env("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(",") if h.strip()]
    if _allowed
    else (["*"] if DEBUG else ["www.customr-club.rirashop.com", "customr-club.rirashop.com"])
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my apps
    "module_account",
    "module_product",
    "module_api_v1",
    "module_shop",

    # installed apps
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
]

if ENABLE_OPENAPI:
    INSTALLED_APPS.append("drf_spectacular")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CustomerClub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CustomerClub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

AUTH_USER_MODEL = "module_account.User"

from CustomerClub.database import build_databases  # noqa: E402

DATABASES = build_databases(base_dir=BASE_DIR, debug=DEBUG)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
# TIME_ZONE = "Iran"
TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT= BASE_DIR / "media"
MEDIA_URL= "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "CustomerClub.exceptions.persian_exception_handler",
}
if ENABLE_OPENAPI:
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes= 5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days= 1),
}

if ENABLE_OPENAPI:
    SPECTACULAR_SETTINGS = {
        "TITLE": "CustomerClub Kiosk API",
        "DESCRIPTION": "Public kiosk REST API",
        "VERSION": "1.0.0",
        "SERVE_INCLUDE_SCHEMA": False,
    }

if DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {"class": "logging.StreamHandler"},
        },
        "loggers": {
            "django": {"level": "WARNING", "handlers": ["console"]},
            "django.db.backends": {"level": "WARNING", "handlers": ["console"]},
        },
    }

CORS_ORIGIN_ALLOW_ALL= True


PHONE_NUMBER_VERIFICATION_CODE_LENGTH= 4
PHONE_NUMBER_VERIFICATION_CODE_LIFE= 300 # seconds (5 min)
PHONE_NUMBER_VERIFICATION_CODE_SEND_LIMIT= 60 # seconds (1 min)

# Limit SMS resend attempts per login "session" (cache TTL window).
SMS_MAX_RESENDS_PER_SESSION = int(_env("SMS_MAX_RESENDS_PER_SESSION", "5"))
SMS_RESEND_SESSION_TTL = int(_env("SMS_RESEND_SESSION_TTL", str(PHONE_NUMBER_VERIFICATION_CODE_LIFE)))

SMSIR_API_KEY = _env("SMSIR_API_KEY", "rs2ZenlByafdlUkNeHhNSajIfLX3RXMnswbvZlWkhrTOwBTl")
SMSIR_LINE_NUMBER = _env("SMSIR_LINE_NUMBER", "30007732011066")
SMSIR_TEMPLATE_ID = _env("SMSIR_TEMPLATE_ID", "493815")
SMS_IR_ENABLED = _env("SMS_IR_ENABLED", "true").lower() in ("1", "true", "yes", "on")
SMS_DEBUG_MODE = _env("SMS_DEBUG_MODE", "false").lower() in ("1", "true", "yes", "on")
SMS_IR_TIMEOUT = int(_env("SMS_IR_TIMEOUT", "10")) 

SMS_IR_API_KEY = SMSIR_API_KEY
SMS_IR_LINE_NUMBER = SMSIR_LINE_NUMBER
SMS_IR_TEMPLATE_ID = SMSIR_TEMPLATE_ID

USER_OFFER_SCORE_LIMIT= 1000

# Cache for one-time NFC login tokens (use Redis in production for multi-worker)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "nfc-login",
    }
}

# NFC bridge (hardware script) → backend; optional secret for production
NFC_BRIDGE_SECRET = _env("NFC_BRIDGE_SECRET", "")
NFC_LOGIN_TOKEN_TTL = int(_env("NFC_LOGIN_TOKEN_TTL", "60"))  # seconds
FRONTEND_BASE_URL = _env("FRONTEND_BASE_URL", "http://127.0.0.1:5002")

# Management server integration (product/offer source of truth)
MANAGEMENT_API_BASE_URL = _env("MANAGEMENT_API_BASE_URL", "http://127.0.0.1:8000")
MANAGEMENT_SERVICE_API_KEY = _env("MANAGEMENT_SERVICE_API_KEY", "")
MANAGEMENT_API_TIMEOUT = int(_env("MANAGEMENT_API_TIMEOUT", "15"))
# Cache integration API responses on the kiosk server (seconds).
MANAGEMENT_CACHE_TTL_SHOPS = int(_env("MANAGEMENT_CACHE_TTL_SHOPS", "600"))
MANAGEMENT_CACHE_TTL_CATALOG = int(_env("MANAGEMENT_CACHE_TTL_CATALOG", "300"))
MANAGEMENT_CACHE_TTL_OFFERS = int(_env("MANAGEMENT_CACHE_TTL_OFFERS", "120"))
MANAGEMENT_CACHE_STALE_MULTIPLIER = int(_env("MANAGEMENT_CACHE_STALE_MULTIPLIER", "24"))
PUBLIC_API_BASE_URL = _env("PUBLIC_API_BASE_URL", "http://127.0.0.1:8001")

# When True (default), the kiosk stores no business data locally; management is the only database.
STATELESS_KIOSK = _env("STATELESS_KIOSK", "true").lower() in ("1", "true", "yes", "on")
